Vagrant.configure("2") do |config|
	config.vm.define "centos7" do |node|
	  node.vm.box = "centos/7"
	  node.vm.box_version = "1705.01"
	  node.vm.box_check_update = false

	  node.vm.provision "shell", inline: "echo This box contains CentOS 7 64-bit."
	  node.vm.hostname = "centos"
	  node.vm.network "public_network", ip: "192.168.31.216"
	  
	  node.vm.provider "virtualbox" do |v|
	    v.name = "centos"
	    v.memory = 4096
	    v.cpus = 2
	  end
	end
end